"""Step 3: write svg/ — every shape x three colourways, tight bounds, viewBox
from 0 0, fills only, one path per colour."""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
import geom
from geom import d, transform, single
OUT = os.path.join(HERE, "..", "svg"); os.makedirs(OUT, exist_ok=True)
RED, CHAR, WHITE = "#952926", "#3F3F41", "#FFFFFF"
DESC = {
 "lockup": "the full badge: arched name, crossed tools, ribbon, EST. 2017 — the primary logo",
 "mark": "ribbon over crossed tools — the badge without the name, for 40-120px",
 "mark-small": "ribbon and tools, lettering removed — for 32px and below only (favicon). Never the logo",
 "wordmark": "BIGGY SMALLZ, straightened from the badge's own letters, over the ribbon",
 "wordmark-wide": "one line: name left, ribbon right — for wide, short spaces (site header)",
}
def bounds_of(parts):
    bs = [p.bounds for p in parts]
    return min(b[0] for b in bs), min(b[1] for b in bs), max(b[2] for b in bs), max(b[3] for b in bs)
def svg(name, variant, layers):
    x0, y0, x1, y1 = bounds_of([p for _, p in layers])
    w, h = x1 - x0, y1 - y0
    body = "".join(f'<path fill="{fill}" d="{d(transform(p, 1, -x0, -y0))}"/>' for fill, p in layers)
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w:.2f} {h:.2f}" width="{w:.0f}" height="{h:.0f}">'
            f'<!-- Biggy Smallz Spitmasters · {name}-{variant} · {DESC[name]} · redrawn by TK Studio from the 2017 logo · generated by _build/build_svg.py, do not hand-edit -->'
            f'{body}</svg>\n')
S = geom.shapes()
written = []
for name, s in S.items():
    for variant, ink in (("charcoal", CHAR), ("white", WHITE)):
        layers = [(ink, s["ink"]), (RED, s["red"])] + ([(WHITE, s["paper"])] if "paper" in s else [])
        open(os.path.join(OUT, f"{name}-{variant}.svg"), "w").write(svg(name, variant, layers)); written.append(f"{name}-{variant}")
    open(os.path.join(OUT, f"{name}-single.svg"), "w").write(svg(name, "single", [("currentColor", single(s))])); written.append(f"{name}-single")
print(len(written), "svg files")
