"""Step 4: png/, social/, favicon/ from svg/. Everything rendered natively at
its final size by Chromium (no downscaling one big image)."""
import os, sys, io, math
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
import numpy as np
from PIL import Image
import render
ROOT = os.path.join(HERE, "..")
SVG = lambda n: open(os.path.join(ROOT, "svg", n + ".svg")).read()
BLACK, WHITE, BONE = "#161517", "#FFFFFF", "#F4EFE6"
SHAPES = ["lockup", "mark", "mark-small", "wordmark", "wordmark-wide"]
def mk(p): os.makedirs(p, exist_ok=True); return p

# ---- png/: every shape, two solid colourways, 512/1024/2048 wide, transparent
out = mk(os.path.join(ROOT, "png"))
for s in SHAPES:
    for v in ("charcoal", "white"):
        svg = SVG(f"{s}-{v}"); vw, vh = render.svg_box(svg)
        for W in (512, 1024, 2048):
            H = round(W * vh / vw)
            render.html_to_png(render.place(svg, W, H), W, H, os.path.join(out, f"{s}-{v}-{W}.png"), transparent=True)

# ---- social/: 1080 opaque profile pictures, sized to the circle they'll be cut to
def radius_fit(svg, target_r_frac):
    """Scale so the ink's furthest point from centre sits at target_r_frac of the half-width."""
    N = 540
    vw, vh = render.svg_box(svg)
    tmp = os.path.join(ROOT, "_fit.png")
    render.html_to_png(render.place(svg, N, N), N, N, tmp, transparent=True)
    a = np.array(Image.open(tmp))[..., 3] > 8; os.remove(tmp)
    ys, xs = np.nonzero(a); r = np.sqrt((xs - N/2 + .5)**2 + (ys - N/2 + .5)**2).max()
    return (target_r_frac * N/2) / r      # factor to apply to 'contain' size
soc = mk(os.path.join(ROOT, "social"))
PROFILES = [("profile-badge-white", "lockup-charcoal", WHITE, 0.90),
            ("profile-badge-black", "lockup-white", BLACK, 0.90),
            ("profile-mark-white", "mark-charcoal", WHITE, 0.88),
            ("profile-mark-black", "mark-white", BLACK, 0.88)]
for name, src, bg, rf in PROFILES:
    svg = SVG(src); k = radius_fit(svg, rf)
    pad = (1 - k) / 2
    render.html_to_png(render.place(svg, 1080, 1080, bg=bg, pad=pad), 1080, 1080, os.path.join(soc, name + ".png"))

# ---- favicon/: the favicon cut, cropped square around the crossed tools so the
# ribbon runs edge to edge. The full cut is 1.77:1; fitted whole into a square
# the ribbon became a 3px line at 16px (first render, 2026-09-23). Each size is
# rendered natively, not downscaled.
fav = mk(os.path.join(ROOT, "favicon"))
import re, geom
small = SVG("mark-small-charcoal")
ms = geom.shapes()["mark-small"]
ix0 = min(ms["ink"].bounds[0], ms["red"].bounds[0]); iy0 = min(ms["ink"].bounds[1], ms["red"].bounds[1])
tb = ms["ink"].bounds                                  # the crossed tools
side = max(tb[2]-tb[0], tb[3]-tb[1]) * 1.04
cx, cy = (tb[0]+tb[2])/2 - ix0, (tb[1]+tb[3])/2 - iy0
VB = f"{cx-side/2:.1f} {cy-side/2:.1f} {side:.1f} {side:.1f}"
inner = re.sub(r"<!--.*?-->", "", re.sub(r"^<svg[^>]*>", "", small.strip()).replace("</svg>", ""))
def fav_svg(bg_rx):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{VB}"><!-- Biggy Smallz Spitmasters · favicon · the favicon cut, never the logo · generated by _build/build_raster.py -->'
            f'<rect x="{cx-side/2:.1f}" y="{cy-side/2:.1f}" width="{side:.1f}" height="{side:.1f}" rx="{side*bg_rx:.1f}" fill="{WHITE}"/>{inner}</svg>\n')
open(os.path.join(fav, "favicon.svg"), "w").write(fav_svg(0.18))
for sz in (16, 32, 48):
    render.html_to_png(render.place(fav_svg(0.18), sz, sz), sz, sz, os.path.join(fav, f"favicon-{sz}.png"), transparent=True)
render.html_to_png(render.place(fav_svg(0), 180, 180), 180, 180, os.path.join(fav, "apple-touch-icon-180.png"))
ims = [Image.open(os.path.join(fav, f"favicon-{s}.png")).convert("RGBA") for s in (16, 32, 48)]
ims[2].save(os.path.join(fav, "favicon.ico"), format="ICO", sizes=[(16, 16), (32, 32), (48, 48)], append_images=ims[:2])
render.close()
print("raster done")
