"""Writes README.md from the test results, so its numbers can't drift."""
import os, json
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.join(HERE, "..")
T = lambda n: json.load(open(os.path.join(HERE, "tests", n)))
mins, prod, con, fid = T("minimums.json"), T("production.json"), T("contrast.json"), T("fidelity.json")
fails = [p for p in con if not p["body_text"]]
md = f"""# Biggy Smallz Spitmasters — brand identity

Martin "Biggy" Mhlongo's 2017 badge, redrawn cleanly so it works everywhere. Open **`brand-guide.html`** first: it works offline, on a phone.

*Every file here is generated by `_build/`. Don't hand-edit them. Change the scripts and rebuild.*

## Which file for which job

| Job | File |
|---|---|
| Printer, signwriter, embroiderer, screen printer | `svg/lockup-single.svg` (one ink: they choose the colour) |
| Anything on a light ground (menus, proposals, documents) | `svg/lockup-charcoal.svg` · `png/lockup-charcoal-2048.png` |
| Anything on a dark ground (the site, the fire, black shirts) | `svg/lockup-white.svg` · `png/lockup-white-2048.png` |
| Instagram profile picture | `social/profile-badge-white.png` (the familiar one) |
| WhatsApp profile picture | `social/profile-mark-white.png` (the mark holds at 40–56px, which is where WhatsApp shows it) |
| Small spaces: a stamp, a sleeve, a box | `svg/mark-*.svg` |
| Page header, letterhead | `svg/wordmark-*.svg` |
| Site header, email signature, banner | `svg/wordmark-wide-*.svg` |
| Website icon | `favicon/` (all files; `favicon.svg` carries its own white field) |
| Bios for Instagram, WhatsApp, Google | `bios.md` |
| Proof that the profile pictures hold small | `social/_circle-crop-check.png` |

**Why there's no PNG of `-single`:** a one-colour file exists so the person making the thing can choose the colour. Flattening it to a picture takes that choice away. That's deliberate, not an omission.

## The cuts

| Cut | What it is | Smallest on screen | Smallest in print |
|---|---|---|---|
| `lockup` | the full badge — the logo | {mins['min_px']['lockup']}px | {mins['min_mm']['lockup']}mm |
| `mark` | ribbon over crossed tools, no name | {mins['min_px']['mark']}px | {mins['min_mm']['mark']}mm |
| `wordmark` | his letters set straight, over the ribbon | {mins['min_px']['wordmark']}px | {mins['min_mm']['wordmark']}mm |
| `wordmark-wide` | one line: name, then ribbon | {mins['min_px']['wordmark-wide']}px | {mins['min_mm']['wordmark-wide']}mm |
| `mark-small` | ribbon without lettering — **favicon only, 16–32px, never the logo** | 16px | not for print |

Colourways: `-charcoal` (for light grounds), `-white` (for dark grounds), `-single` (one ink, `currentColor`).

## Palette

Spitmasters Red `#952926` · Charcoal `#3F3F41` (both sampled from the 2017 logo) · Jacket Black `#161517` · Bone `#F4EFE6` · White `#FFFFFF`. Approved by TK, 2026-09-23.

Pairings that fail as text ({len(fails)}): {"; ".join(f"{p['a']} / {p['b']} {p['ratio']}:1" for p in fails)}. Red is never text on a dark ground.

## Type

**Oswald** (600, 700) for headlines, which is the loud voice. **Source Serif 4** (400, italic, 600) for everything you read, which is the quiet voice. Both are free (SIL Open Font License, copies in `_build/fonts/`).

## Rebuild

```
pip install numpy scipy scikit-image pillow svgelements skia-pathops fonttools brotli playwright
python -m playwright install chromium
# plus potrace: https://potrace.sourceforge.net (on PATH)
python _build/build_all.py
```

## Decisions, dated

- **2026-09-23 · Route 1: redraw faithfully.** Chosen by TK and Martin over "evolve" and "replace". The badge is on his jacket and in years of photos.
- **2026-09-23 · The source is `_build/source/logo-2017.png`,** the site's 1600px logo. TK confirmed no original vector or designer is known, so it's traced (potrace, at 2× for smooth curves).
- **Cleaned:** the speckle texture inside SPITMASTERS is removed (small holes filled). Nothing else about the design was changed. Measured: the redraw's silhouette overlaps the 2017 logo's by **{fid['silhouette_iou']*100:.1f}%** (`_build/tests/fidelity.json`).
- **Fork tines blunted by 6px.** A true point drops out of a stitch. 20px (the 1.5% guideline) and 10px were tried first and cut the tines too short to read as his fork. See `_build/trace.py`.
- **The wordmarks use his own letters,** straightened off the arch (`_build/straighten.py`), not a substitute font. His original fonts aren't identified.
- **The favicon cut drops the ribbon lettering,** which is noise at 32px and below anyway (reduction test).
- **Print minimums** assume a 0.2mm finest-line floor. `[TK to confirm with the printer — open]`
- **Known limit, not fixed:** the fork's tines and the EST. 2017 lettering are thinner than the 1.5%-of-width embroidery guideline (5th-percentile ink detail: badge {prod['lockup']['ink']['p5_pct']}%, mark {prod['mark']['ink']['p5_pct']}%). Thickening them would change his mark. It's already stitched well on the jacket, so get the digitiser's OK before stitching smaller, and use the mark for small embroidery. **Accepted as-is by TK, 2026-09-24.**
- **Type chosen at this checkpoint:** Oswald is closest in shape to the ribbon lettering of the three shortlisted. Source Serif 4 is quieter than Lora for long menus. **Approved by TK, 2026-09-24.**

## Tests

In `_build/tests/`: `reduction.png`, `contrast.json`, `production.json`, `minimums.json`, `fidelity.json`, `single-ink-*.png`. The circle-crop proof ships in `social/`.
"""
open(os.path.join(ROOT, "README.md"), "w").write(md)
