"""Generates ../bios.md. Edit the copy HERE, then run:  python3 _build/bios.py
Counts are computed, never estimated (deliverable-spec §6).
Two counts per block: Python code points, and UTF-16 units (what JavaScript-built
apps like Instagram and WhatsApp count, so emoji cost more). Gate uses the stricter.
Where published limits disagree, the stricter one is used and noted.
"""
from pathlib import Path

def u16(s): return len(s.encode("utf-16-le")) // 2

BLOCKS = [
 # (platform, field, limit, limit source, text)
 ("Instagram @biggysmallzspitmasters", "Name", 30,
  "30 — replug.io (some sources say 64; stricter used)",
  "Biggy Smallz Spitmasters"),
 ("Instagram @biggysmallzspitmasters", "Category", None, "picked from Instagram's list", "Personal chef  (keep: Martin's own choice)"),
 ("Instagram @biggysmallzspitmasters", "Bio", 150, "150 — replug.io",
  "From spitbraai to elegant 7-course meals, brought to wherever your table is. The #GetInMyBelly experience by chef @biggy013 and team 👨🏿‍🍳"),
 ("Instagram @biggysmallzspitmasters", "Link", None, "", "biggysmallzspitmasters.co.za"),
 ("WhatsApp Business", "Business name", None, "", "Biggy Smallz Spitmasters"),
 ("WhatsApp Business", "About", 139, "139 — wha.tools, Vonage",
  "Get in my belly 👨🏿‍🍳 Spitbraai to 7 courses, made personal."),
 ("WhatsApp Business", "Business description", 256,
  "256 — Vonage (other sources say 512; stricter used)",
  "Spitbraai and plated dining by chef Martin \"Biggy\" Mhlongo and team, since 2017. Weddings, birthdays, corporate and site functions, festivals. Based in Mbombela, brought to wherever your table is. Message us and Biggy will get back to you himself."),
 ("WhatsApp Business", "Website", None, "", "https://biggysmallzspitmasters.co.za"),
 ("WhatsApp click-to-chat opener", "Prefilled message (Martin's own, unchanged)", None, "", "Hey Biggy! Time for my \"GET IN MY BELLY\" experience...."),
 ("Google Business Profile", "Description", 750,
  "750, ~250 shown before \"more\"; no URLs, no promotions, no misspellings — BrightLocal",
  "Biggy Smallz Spitmasters is a spitbraai and personal chef catering business run by Martin \"Biggy\" Mhlongo, cooking since 2017. From a whole spitbraai over the fire to a plated 7-course tasting menu, Biggy and his team bring it to wherever your table is: weddings, milestone birthdays, family celebrations, corporate and construction-site functions, festivals and large gatherings. Based in Mbombela (Nelspruit) in the Mpumalanga Lowveld, and travelling across South Africa and into Mozambique. Biggy has cooked on Ultimate Braai Master, Come Dine With Me SA and Rate My Plate, and has been the South African pitmaster at the Mozambique Barbecue Festival. Get in my belly."),
]

out = ["# Biggy Smallz Spitmasters — bios",
       "",
       "*Generated by `_build/bios.py` — do not hand-edit; change the script and re-run.*",
       "",
       "Counts: **cp** = characters (code points), **u16** = UTF-16 units, which is how the apps count, so an emoji costs more. The gate uses u16.",
       ""]
fails = 0
cur = None
for plat, field, lim, src, text in BLOCKS:
    if plat != cur:
        out += ["", f"## {plat}", ""]; cur = plat
    cp, w = len(text), u16(text)
    if lim:
        ok = w <= lim
        fails += (not ok)
        status = f"{'✓' if ok else '✗'} {w}/{lim} u16 ({cp} cp) · headroom {lim-w} · limit: {src}"
    else:
        status = f"{w} u16 ({cp} cp) · no limit that matters here"
    out += [f"**{field}** — {status}", "", "```", text, "```", ""]
gbp = [b for b in BLOCKS if b[0].startswith("Google")][0][4]
out += ["", "### Google: what shows before \"more\" (first 250 characters)", "", "```", gbp[:250], "```", ""]
out += ["---", "", f"**Gate: {len([b for b in BLOCKS if b[2]])} limited blocks, {fails} over limit.**"]
Path(__file__).resolve().parent.parent.joinpath("bios.md").write_text("\n".join(out), encoding="utf-8")
print(f"limited blocks: {len([b for b in BLOCKS if b[2]])}, over limit: {fails}")
for plat, field, lim, src, text in BLOCKS:
    if lim: print(f"  {field:22} {u16(text):4}/{lim}  cp={len(text)}")
